### PR TITLE
Routing

### PR DESCRIPTION
**Pull request by rschristian**
Try something more along the lines of this. Reduces line count and removes a dependency. The Preact CLI has async component loading built right in. Preact itself has an experimental version too.

### CODE REVIEW

**Review by RomanistHere — APPROVED** [review]

**Comment by rschristian** [comment]
Sorry, late here so I won't be able to get back to you for a few hours if you comment further.

**Comment by RomanistHere** [comment]
> Sorry, late here so I won't be able to get back to you for a few hours if you comment further.

Thank you for your help!

**Review by RomanistHere — APPROVED** [review]

**Comment by rschristian** [comment]
No problem. Certainly let me know if I can help further, just gotta get some sleep first:)

**Comment by RomanistHere** [comment]
> No problem. Certainly let me know if I can help further, just gotta get some sleep first:)

Async things are not working well for me, I'm getting build errors when I'm trying to suspense/lazy router. Otherwise everything is working just fine. 

Thank you again for some clarifications. There are a lot of non-obvious things about this framework. And big lack of documentation and examples. I'll try to write an article with some pointers how to migrate React to Preact later.

Cya!

**Comment by rschristian** [comment]
Well you have to remember that you're not just switching out libraries (React -> Preact) but also switching out build tools entirely. 

Preact ultimately is not a framework, but a library, just like React, and therefore the ecosystem is more of an Ikea if you will. You add the parts you need or want, keep out the ones you don't. Not ever part works for all use cases and isn't meant to often.

**Comment by rschristian** [comment]
That being said, documentation updates via PR are always appreciated

**Comment by RyanChristian4427** [comment]
Also, uncommenting your async router seems to work fine on my end with a little edit of your `preact.config.js` file.

**Comment by rschristian** [comment]
Just remembered, `Suspense` is not going to work when prerendering as prerendering in Node doesn't wait for async operations to resolve. That's probably the issue you're having.

**Pull request closed without merging**
